name: Generate SDKs and create PRs for individual language repositories

# env:
#   ANALYTICS_API_USERNAME_SERIAL: ${{ secrets.ANALYTICS_API_USERNAME_SERIAL }}
#   ANALYTICS_API_PASSWORD: ${{ secrets.ANALYTICS_API_PASSWORD }} 

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        run: sudo snap install hub --classic
    
      - name: Check out Analytics API dotnet SDK
        uses: actions/checkout@v2
        with:
          repository: afernandes85/analyticsapi-engines-dotnet-sdk
          path: analyticsapi-engines-dotnet-sdk
          fetch-depth: 0
          token: ${{ secrets.USER_API_KEY }}

      - name: Check out Analytics API SDK Generator
        uses: actions/checkout@v2
        with:
          repository: afernandes85/analyticsapi-engines-sdk-generator
          path: analyticsapi-engines-sdk-generator
          fetch-depth: 0

      - name: Generate new SDK using Open API Generator Custom Docker image
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}/analyticsapi-engines-sdk-generator:/generator \
          -v ${GITHUB_WORKSPACE}/analyticsapi-engines-dotnet-sdk:/sdk \
          arnoldfernandes/openapi-generator-cli-custom:4.2.2 generate \
          --generator-name CustomCSharpNetCoreClientCodegen \
          --input-spec /generator/openapi-schema.json \
          --output /sdk/Engines \
          --config /generator/dotnet/openapi-generator-config.json \
          --http-user-agent engines-api/3.0.0/csharp \
          --template-dir /generator/dotnet/templates \
          --skip-validate-spec

      - name: Build new SDK
        run: docker run --rm -v ${GITHUB_WORKSPACE}/analyticsapi-engines-dotnet-sdk/Engines:/app -w /app mcr.microsoft.com/dotnet/core/sdk:2.2 dotnet build -c release
      
      - name: Get the version
        id: vars
        run: echo ::set-output name=version::$(<./Engines/.openapi-generator/VERSION)

      - name: Raise pull request
        run: |
          cd analyticsapi-engines-dotnet-sdk

          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER }}"

          version=$(<./Engines/.openapi-generator/VERSION)
          branch_name="feat/sdk/v$version"
          
          if [ `git branch --list $branch_name` ]
          then
            git checkout $branch_name
            git status
            git add -A .
            git commit -m "feat(sdk): v$version"
            echo "Committed all the changes"
            
            git push origin $branch_name
            echo "Pushed all the changes to remote location"
          else
            git checkout -b $branch_name
            git status
            git add -A .
            git commit -m "feat(sdk): v$version"
            echo "Committed all the changes"
            
            git push origin $branch_name
            echo "Pushed all the changes to remote location"
            
            export GITHUB_USER=${{ secrets.USER }}
            export GITHUB_TOKEN=${{ secrets.USER_API_KEY }}
            hub pull-request -m "feat(sdk): Updating SDK" -h $branch_name
          fi         
  
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        run: sudo snap install hub --classic
    
      - name: Check out Analytics API python SDK
        uses: actions/checkout@v2
        with:
          repository: afernandes85/analyticsapi-engines-python-sdk
          path: analyticsapi-engines-python-sdk
          fetch-depth: 0
          token: ${{ secrets.USER_API_KEY }}

      - name: Check out Analytics API SDK Generator
        uses: actions/checkout@v2
        with:
          repository: afernandes85/analyticsapi-engines-sdk-generator
          path: analyticsapi-engines-sdk-generator
          fetch-depth: 0

      - name: Generate new SDK using Open API Generator Custom Docker image
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}/analyticsapi-engines-sdk-generator:/generator \
          -v ${GITHUB_WORKSPACE}/analyticsapi-engines-python-sdk:/sdk \
          arnoldfernandes/openapi-generator-cli-custom:4.2.2 generate \
          --generator-name CustomPythonClientCodegen \
          --input-spec /generator/openapi-schema.json \
          --output /sdk/engines \
          --config /generator/python/openapi-generator-config.json \
          --http-user-agent engines-api/3.0.0/python \
          --template-dir /generator/python/templates \
          --skip-validate-spec

      # - name: Build new SDK
      #   run: docker run --rm -v ${GITHUB_WORKSPACE}/analyticsapi-engines-python-sdk/Engines:/app -w /app mcr.microsoft.com/dotnet/core/sdk:2.2 dotnet build -c release
      
      - name: Raise pull request
        run: |
          cd analyticsapi-engines-python-sdk
          
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER }}"

          branch_name="feat/sdk/updating-`date +%s`" 
          git checkout -b $branch_name
          git status
          git add -A .
          git commit -m "feat(sdk): Updating SDK"
          echo "Committed all the changes"
          
          git push origin $branch_name
          echo "Pushed all the changes to remote location"
          
          export GITHUB_USER=${{ secrets.USER }}
          export GITHUB_TOKEN=${{ secrets.USER_API_KEY }}
          hub pull-request -m "feat(sdk): Updating SDK" -h $branch_name

