name: Generate SDKs and create PRs for individual language repositories

env:
  USER_API_KEY: ${{ secrets.USER_API_KEY }}
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER: ${{ secrets.USER }}
  OPENAPI_GENERATOR_VERSION: 4.2.2
  GITHUB_DOTNET_SDK_REPO: afernandes85/analyticsapi-engines-dotnet-sdk
  GITHUB_DOTNET_SDK_FOLDER: Engines
  GITHUB_PYTHON_SDK_REPO: afernandes85/analyticsapi-engines-python-sdk
  GITHUB_PYTHON_SDK_FOLDER: fds.analyticsapi.engines

on:
  pull_request:
    branches: [ master ]

jobs:
  dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        run: sudo snap install hub --classic
    
      - name: Check out SDK repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_DOTNET_SDK_REPO }}
          path: sdk
          fetch-depth: 0
          token: ${{ env.USER_API_KEY }}

      - name: Check out Generator repository
        uses: actions/checkout@v2
        with:
          path: generator
          fetch-depth: 0

      - name: Generate SDK
        run: generator/scripts/generate-sdk.sh $OPENAPI_GENERATOR_VERSION dotnet CustomCSharpNetCoreClientCodegen

      # - name: Build new SDK
      #   run: docker run --rm -v ${GITHUB_WORKSPACE}/generator/languages/dotnet/sdk:/app -w /app mcr.microsoft.com/dotnet/core/sdk:2.2 dotnet build -c release
      
      - name: Raise pull request on SDK repository
        run: generator/scripts/raise-pull-request.sh dotnet $GITHUB_DOTNET_SDK_FOLDER
  
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        run: sudo snap install hub --classic
    
      - name: Check out SDK repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_PYTHON_SDK_REPO }}
          path: sdk
          fetch-depth: 0
          token: ${{ env.USER_API_KEY }}

      - name: Check out Generator repository
        uses: actions/checkout@v2
        with:
          path: generator
          fetch-depth: 0

      - name: Generate SDK
        run: generator/scripts/generate-sdk.sh $OPENAPI_GENERATOR_VERSION python CustomPythonClientCodegen
      
      # - name: Build new SDK
      #   run: docker run --rm -v ${GITHUB_WORKSPACE}/sdk/Engines:/app -w /app mcr.microsoft.com/dotnet/core/sdk:2.2 dotnet build -c release
      
      - name: Raise pull request on SDK repository
        run: generator/scripts/raise-pull-request.sh python $GITHUB_PYTHON_SDK_FOLDER
