name: Generate SDKs and create PRs for individual language repositories

env:
  USER_API_KEY: ${{ secrets.USER_API_KEY }}
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER: ${{ secrets.USER }}
  GITHUB_DOTNET_SDK_REPO: afernandes85/analyticsapi-engines-dotnet-sdk
  GITHUB_DOTNET_SDK_FOLDER: Engines
  GITHUB_PYTHON_SDK_REPO: afernandes85/analyticsapi-engines-python-sdk
  GITHUB_PYTHON_SDK_FOLDER: fds.analyticsapi.engines

on:
  pull_request:
    branches: [ master ]

jobs:
  dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        run: sudo snap install hub --classic
    
      - name: Check out Analytics API dotnet SDK
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_DOTNET_SDK_REPO }}
          path: sdk
          fetch-depth: 0
          token: ${{ env.USER_API_KEY }}

      - name: Check out Analytics API SDK Generator
        uses: actions/checkout@v2
        with:
          path: generator
          fetch-depth: 0

      - name: Build the Docker image
        run: |
          docker build --build-arg VERSION=4.2.2 \
          -t openapi-generator-cli-custom \
          -f ${GITHUB_WORKSPACE}/generator/openapi-generator/Dockerfile \
          ${GITHUB_WORKSPACE}/generator/openapi-generator

      - name: Generate new SDK using Open API Generator Custom Docker image
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}/generator:/generator \
          openapi-generator-cli-custom generate \
          --generator-name CustomCSharpNetCoreClientCodegen \
          --input-spec /generator/openapi-schema.json \
          --output /generator/languages/dotnet/sdk \
          --config /generator/languages/dotnet/openapi-generator-config.json \
          --template-dir /generator/languages/dotnet/templates \
          --skip-validate-spec

      # - name: Build new SDK
      #   run: docker run --rm -v ${GITHUB_WORKSPACE}/generator/languages/dotnet/sdk:/app -w /app mcr.microsoft.com/dotnet/core/sdk:2.2 dotnet build -c release
      
      - name: Raise pull request
        run: generator/scripts/raise-pull-request.sh dotnet $GITHUB_DOTNET_SDK_FOLDER
  
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Install Hub
        run: sudo snap install hub --classic
    
      - name: Check out Analytics API python SDK
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_PYTHON_SDK_REPO }}
          path: sdk
          fetch-depth: 0
          token: ${{ env.USER_API_KEY }}

      - name: Check out Analytics API SDK Generator
        uses: actions/checkout@v2
        with:
          path: generator
          fetch-depth: 0

      - name: Build the Docker image
        run: |
          docker build --build-arg VERSION=4.2.2 \
          -t openapi-generator-cli-custom \
          -f ${GITHUB_WORKSPACE}/generator/openapi-generator/Dockerfile \
          ${GITHUB_WORKSPACE}/generator/openapi-generator

      - name: Generate new SDK using Open API Generator Custom Docker image
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}/generator:/generator \
          openapi-generator-cli-custom generate \
          --generator-name CustomPythonClientCodegen \
          --input-spec /generator/openapi-schema.json \
          --output /generator/languages/python/sdk \
          --config /generator/languages/python/openapi-generator-config.json \
          --template-dir /generator/languages/python/templates \
          --skip-validate-spec

      # - name: Build new SDK
      #   run: docker run --rm -v ${GITHUB_WORKSPACE}/sdk/Engines:/app -w /app mcr.microsoft.com/dotnet/core/sdk:2.2 dotnet build -c release
      
      - name: Raise pull request
        run: generator/scripts/raise-pull-request.sh python $GITHUB_PYTHON_SDK_FOLDER
