name: Generate SDKs and raise PRs in individual language repositories

env:
  USER_API_KEY: ${{ secrets.USER_API_KEY }}
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER: ${{ secrets.USER }}
  OPENAPI_GENERATOR_VERSION: 4.2.2
  GITHUB_DOTNET_SDK_REPO: afernandes85/analyticsapi-engines-dotnet-sdk
  GITHUB_DOTNET_SDK_FOLDER: Engines
  GITHUB_PYTHON_SDK_REPO: afernandes85/analyticsapi-engines-python-sdk
  GITHUB_PYTHON_SDK_FOLDER: fds.analyticsapi.engines

on:
  pull_request:
    branches: [ master ]

jobs:
  dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Check out SDK repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_DOTNET_SDK_REPO }}
          path: sdk
          fetch-depth: 0
          token: ${{ env.USER_API_KEY }}

      - name: Check out Generator repository
        uses: actions/checkout@v2
        with:
          path: generator

      - name: Generate SDK
        run: generator/scripts/generate-sdk.sh $OPENAPI_GENERATOR_VERSION dotnet CustomCSharpNetCoreClientCodegen

      - name: Raise pull request on SDK repository
        run: generator/scripts/raise-pull-request.sh dotnet $GITHUB_DOTNET_SDK_FOLDER
  
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Check out SDK repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_PYTHON_SDK_REPO }}
          path: sdk
          fetch-depth: 0
          token: ${{ env.USER_API_KEY }}

      - name: Check out Generator repository
        uses: actions/checkout@v2
        with:
          path: generator

      - name: Generate SDK
        run: generator/scripts/generate-sdk.sh $OPENAPI_GENERATOR_VERSION python CustomPythonClientCodegen
      
      - name: Raise pull request on SDK repository
        run: generator/scripts/raise-pull-request.sh python $GITHUB_PYTHON_SDK_FOLDER

  java:
    runs-on: ubuntu-latest

    steps:
      - name: Check out SDK repository
        if: env.GITHUB_JAVA_SDK_REPO
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GITHUB_JAVA_SDK_REPO }}
          path: sdk
          fetch-depth: 0
          token: ${{ env.USER_API_KEY }}

      - name: Check out Generator repository
        if: env.GITHUB_JAVA_SDK_REPO
        uses: actions/checkout@v2
        with:
          path: generator

      - name: Generate SDK
        if: env.GITHUB_JAVA_SDK_REPO
        run: generator/scripts/generate-sdk.sh $OPENAPI_GENERATOR_VERSION java CustomJavaClientCodegen
      
      - name: Raise pull request on SDK repository
        if: env.GITHUB_JAVA_SDK_REPO
        run: generator/scripts/raise-pull-request.sh java $GITHUB_JAVA_SDK_FOLDER
